### ISSUE TITLE
Only betting bailout every time in tournaments

### ISSUE THREAD

**Issue by Leurus** [Pauan/SaltyBetBot#10]
Since the tournament update, the bot is now betting 4100 (my bailout amount) every bet in tournaments. I'm assuming this is a bug?

I'm also curious how you improved the tournament algorithm if you wouldn't mind explaining that?

**Comment by Pauan** [comment]
Oops, that's a mistake from the recent changes, I fixed it.

The improvements are just switching it from winrate to ELO. The benefits are quite small, since winrate was already close to optimal.
