### ISSUE TITLE
The bot is not betting

### ISSUE THREAD

**Issue by Zaeems** [Pauan/SaltyBetBot#13]
I have cloned the git, pulled (already up to date), then opened a tab with saltybet.com, the extension is not betting anything.
I cannot open the chart and records pages (they only say loading...).

**Comment by jborrelli1** [comment]
Hey bud, I am also having issues getting the bot to work. The charts and record work fine for me they take a little to load cause of all the info probably. Go check your error log on the extension page we might be having the same issues. 
Here are the gyazos for the errors i'm getting:
https://gyazo.com/664081290f59b8ebc4b2c57457695ab4
https://gyazo.com/866c4d52c6d6e544794ee93a79f7f9e9

**Comment by Zaeems** [comment]
Same errors
http://prntscr.com/q16r79
http://prntscr.com/q16raw

**Comment by Pauan** [comment]
Could you please click on the `background page` link (right next to `Inspect views` on the Extensions page) and then copy-paste that into here?

**Comment by jborrelli1** [comment]
Finished loading Rust wasm module 'background'
background.js:574 2019-11-23T23:20:51.445Z [src\bin\background\main.rs:364] Initializing...
background.js:574 2019-11-23T23:20:51.451Z [src\bin\background\main.rs:366] Initializing database took 4.865000024437904ms
background.js:574 2019-11-23T23:20:54.628Z [src\bin\background\main.rs:301] Retrieving default records took 3175.7650000508875ms
background.js:574 2019-11-23T23:20:54.640Z [src\bin\background\main.rs:314] Retrieved 247077 default records
background.js:574 2019-11-23T23:21:10.311Z [src\bin\background\main.rs:321] Deleting duplicate records took 18859.629999962635ms
background.js:574 2019-11-23T23:21:10.312Z [src\bin\background\main.rs:354] Deleted 0 records
background.js:574 2019-11-23T23:21:10.312Z [src\bin\background\main.rs:355] Retrieved 247077 current records
background.js:574 2019-11-23T23:21:10.541Z [src\bin\background\main.rs:384] Inserting default records took 228.9149999851361ms
background.js:574 2019-11-23T23:21:10.541Z [src\bin\background\main.rs:390] Inserted 0 records
background.js:574 2019-11-23T23:21:10.542Z [src\bin\background\main.rs:541] Background page started

**Comment by Pauan** [comment]
@jborrelli1 Okay, that all looks fine. Could you try refreshing the SaltyBet tab and see if it works now?

**Comment by jborrelli1** [comment]
Still is not working. My console has a couple errors being thrown and i'm not sure which has to do with the extension. 
https://gyazo.com/d264474e6e353c46aef44af227580d42
^ ive been getting this a couple times but not everytime. 
This and something about a 400 errror request
https://gyazo.com/2f69c31e5f3c5abc1486c9a89a47a93f
Do i have to have the saltybet window highlighted? like have the cursor be in it for the bot to work?

**Comment by Pauan** [comment]
Those errors aren't from this extension, you can safely ignore them.

Just to verify, you are logged in, right? And you can see your current money, the betting box, and the Red and Blue bet buttons, right?

**Comment by jborrelli1** [comment]
Yep, should i relogin?

**Comment by Pauan** [comment]
You can try that, though I doubt it'll help. Do you see any other messages in the console?

**Comment by jborrelli1** [comment]
getting this after the initialized state message from the bot
https://gyazo.com/3add040941dabf2ee599fe3e0bf2c9a9

**Comment by Pauan** [comment]
Okay, none of that is from the extension, are those all of the messages? What about before that point?

**Comment by jborrelli1** [comment]
These are the only other messages i'm getting
https://gyazo.com/e1d2b84f77caa38223aa507b5d1cabf2

**Comment by Pauan** [comment]
No, I mean *all* the messages, including the extension messages.

**Comment by jborrelli1** [comment]
https://gyazo.com/16c69a1fe42c0dd7c2d5df9df96d9d6b
this is everything

**Comment by Pauan** [comment]
Hmmm, okay, everything *seems* okay. Do you have Illuminati (AKA Salty Gold)?

**Comment by jborrelli1** [comment]
yea

**Comment by Pauan** [comment]
Ah, I see the problem, EX9 is currently happening, so the WAIFU4u messages aren't showing up. This is an issue with SaltyBet, not the extension.

You can fix it by visiting `mugen.saltybet.com`

**Comment by Veelohyaa** [comment]
EX9 happened in August, the title just hasn't been changed. The WAIFU4u bot was down for a bit though.

**Comment by Pauan** [comment]
@Veelohyaa Either way, switching to the `mugen` version fixes it (I always use the `mugen` version because it keeps working even during Evo, which is why I wasn't affected by this).

**Comment by jborrelli1** [comment]
It still doesn't seem to be betting. Are you able to set bet amounts? Not sure how the bot works

**Comment by jborrelli1** [comment]
Got this again
https://gyazo.com/ac542a9c6e267f8f8c38301b47ba52e6

**Comment by Pauan** [comment]
@jborrelli1 I just now pushed an update which should fix those errors. [Upgrade](https://github.com/Pauan/SaltyBetBot#how-to-upgrade) and then try again. Keep in mind it will take 20-25 seconds for it to load all the data.

Also make sure you're loading [mugen.saltybet.com](http://mugen.saltybet.com/).
