### ISSUE TITLE
Bet on exhibitions?

### ISSUE THREAD

**Issue by slayer621** [Pauan/SaltyBetBot#14]
Would it be possible to have the bot bet a small amount on exhibitions for exp? Even just $1 would be fine. If the fear is that a bunch of people betting $1 would be suspicious, it could possibly bet some random (each time) amount between $1 and $100.

**Comment by Pauan** [comment]
Betting $1 is doable, yeah, but betting properly isn't possible, because SaltyBet does not give enough information (it does not say which characters are fighting, and it does not say the palettes).

**Comment by Cillu** [comment]
This would be awesome if there was a toggle switch to have it bet during exhibitions so the user has the option for it to run during those periods. Understably, the OP wants to level up his account or just wants to maximize the number of total bets the bot can achieve.

**Comment by Pauan** [comment]
@Cillu The only sort of betting that could happen during exhibitions would be random betting. There just isn't enough information to do actual proper betting during exhibitions.

**Comment by Pauan** [comment]
I just pushed a new version which now bets $1 Red on exhibitions.

It's not possible to do better than that, unless SaltyBet itself changes.

**Comment by Cillu** [comment]
Understood. I realize there is not enough data during exhibitions to have the bot properly bet. So long as it bets 1 dollar on either side (red in this case), this solves the issue of it not doing anything at all. Thank you.
