### ISSUE TITLE
Chrome Crashing

### ISSUE THREAD

**Issue by jmfurm** [Pauan/SaltyBetBot#17]
Chrome asks me to disable the extension. Extension worked fine for approx 10 days to great results. I can use Chrome to its fullest until I go to SaltyBet with the extension active, it will then crash after a few seconds. If I have the extension enabled I can continue to browse all pages. I don't know if this is something on my end or a bug that could be addressed.

**Comment by Pauan** [comment]
Have you [upgraded to the latest version](https://github.com/Pauan/SaltyBetBot#how-to-upgrade)? There were some recent fixes for crashing.

**Comment by Pauan** [comment]
I'm going to assume that this has been fixed, but if it hasn't I can reopen it.
