### ISSUE TITLE
how to perform git pull for upgrade?

### ISSUE THREAD

**Issue by paquin39** [Pauan/SaltyBetBot#22]
Hi not a coder here just a salt miner. Does the upgrade process use the data I generated by betting on matches and improve its knowledge? (Sorry no knowledge of coding here but I got it working). Basically I'm wondering if you could walk through the upgrade process specifically the git pull command. I installed my files on desktop following what you said and have made no other changes. I could completely be misinterpreting what "upgrade means" but if I can use the thousands of matches the bot has bet on to make it better I would love to.

This is where my file is located when I open with git:

andre@LAPTOP-VJM36L9P MINGW64 ~/OneDrive/Desktop/salty/SaltyBetBot-master

From there I haven't the slightest idea to to preform "git pull" command.

**Comment by Pauan** [comment]
> Does the upgrade process use the data I generated by betting on matches and improve its knowledge?

Yes, it combines your personal data with the upgraded data, so no data is lost.

> From there I haven't the slightest idea to to preform "git pull" command.

You just do `cd ~/OneDrive/Desktop/salty/SaltyBetBot-master` and then do `git pull`, that's it.

**Comment by paquin39** [comment]
Ty!

**Comment by paquin39** [comment]
andre@LAPTOP-VJM36L9P MINGW64 ~
$ cd ~/Desktop/salty/SaltyBetBot-master

andre@LAPTOP-VJM36L9P MINGW64 ~/Desktop/salty/SaltyBetBot-master
$ git pull
**fatal: not a git repository (or any of the parent directories): .git**

I removed one drive because I thought that might be bugging it out. I tried understanding git pull with some research and it seems I'm having trouble getting it to pull information to correct place. ( I'm using git bash). 

But thanks for the awesome bot and the work you've put into it! If I'm just not coding competent enough its totally okay haha!

**Comment by Pauan** [comment]
@paquin39 If you do `cd ~/Desktop/salty/SaltyBetBot-master` and then `ls` what does it print?

**Comment by paquin39** [comment]
I think I got it working! I had accidentally downloaded the bot files twice which probably was throwing it off. When I did git pull this time it said  "Already up to date". 

Thanks again for the help, awesome bot!

**Comment by Pauan** [comment]
Great, I'm glad you were able to get it working.
