### ISSUE TITLE
www.twitch.tv refused to connect.

### ISSUE THREAD

**Issue by mizzman101** [Pauan/SaltyBetBot#26]
Hi,

 it keep saying www.twitch.tv refused to connect on chat and on the screen. I tried updating the the bot but it say its already updated.

**Comment by Robmonster** [comment]
I had that when I went to mugen.saltybet.com , just www.saltybet.com was fine.

**Comment by Pauan** [comment]
Yes, it's an issue with the SaltyBet website, not this extension. I have updated the README.
