### ISSUE TITLE
All in while I'm low on salt

### ISSUE THREAD

**Issue by traymundo255** [Pauan/SaltyBetBot#30]
So I'm at my bailout (325) because I'm level 9 on sb but the bot bets all of my money on every bet did I do something wrong?

**Comment by traymundo255** [comment]
Even when I win it still bets all the money from winning too

**Comment by Pauan** [comment]
That's correct, it will continue to all in until you get a significant amount of money, and then it will start betting more cautiously. Because that's the best way to get money as fast as possible.
