### ISSUE TITLE
Bot stopped analysing games - (possibly new Chrome version? See comments)

### ISSUE THREAD

**Issue by Robmonster** [Pauan/SaltyBetBot#32]
Hi there,

Any idea what might make the bot stop working? I've been using ut nicely for the past few months after some teething trouble, but two days ago it dropped back to $1 betting.  No past game analysis shows on the info screen, and if I open the Records page I can see the last game it recorded was dated '2021-02-25T21:40:49.475Z'

I don't believe I've made any config changes.

Any idea what might have happened?

**Comment by Robmonster** [comment]
So, I've tried uninstalling the bot, redownloading from Git and reinstalling, no change. I've tried clearing its records, no change.

It is better $1 each time, so is technically functioning but at no stage does ELO information appear or Win/Upset odds.

It's almost like it thinks everything is an Exhibition or it doesn't know who is fighting. The Waifu4U bot seems to be in chat ok.

**Comment by Robmonster** [comment]
So, not sure what's going on here, reading some of your older closed issues I installed Opera GX browser, and aplpied the same unpacked extension source there, it started working just fine.  I was using Chrome before, perhaps Chrome auto-updated without me realising? 

Anyone else here using this Chrome version?  

Version 88.0.4324.190 (Official Build) (64-bit)

**Comment by Robmonster** [comment]
Looks like that version was released about a week ago, its possible it updated here without me knowing. Curious if anyone else running that version ( or later ) works ok

**Comment by Pauan** [comment]
Since everybody seems to be having issues with Chrome specifically, could you please try it in Brave?

I use `Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)` which works fine for me.

**Comment by Robmonster** [comment]
I installed Opera GX in the end as recommended in another couple of Issue reports here and it worked in there.

However, Ok, Comparing my Chrome display to my Opera display the Chrome one is showing Timestamps next to the chat messages, looks like that's a chat option on Twitch.

Turning chat timestamps off again has made Chrome work once more!

I guess its interfering with the WAIFU4U detection of fighter names .

(Apologies, I thought replying to the github emails wold post that reply here)

**Comment by Pauan** [comment]
@Robmonster Oh, that's very interesting! Let me check and see if I can make it work with timestamps...

**Comment by Pauan** [comment]
Thanks to your tip, I have fixed this in the latest version, please [upgrade](https://github.com/Pauan/SaltyBetBot#how-to-upgrade).
