### ISSUE TITLE
Error when running yarn build

### ISSUE THREAD

**Issue by Leurus** [Pauan/SaltyBetBot#34]
Getting this error when running yarn build, even on a fresh download. Tried upgrading yarn and clearing cache to no avail.

![image](https://user-images.githubusercontent.com/26194213/114512074-b0825380-9c06-11eb-90c3-f2224892a89c.png)

**Comment by Pauan** [comment]
Hmmm, I can't reproduce this, a fresh installation works fine for me.

What are all of the commands that you used?

What version is your `yarn`? Judging by the screenshot, it's quite old.

**Comment by Leurus** [comment]
This is the version I get, and the error I get when I try to update. Thought I already updated also but now it's not letting me.

![image](https://user-images.githubusercontent.com/26194213/114628669-3ba22e80-9c85-11eb-88ca-cd858df4384a.png)

The commands I used in order are:
> rustup install nightly
> rustup override set nightly
> yarn
> yarn build

No issues until I tried to do yarn build

**Comment by Pauan** [comment]
How did you install yarn?

**Comment by Leurus** [comment]
I used the guide you posted to install it. It's been a long time. I haven't
changed anything since it was last working a few months ago.

**Comment by Pauan** [comment]
There are two ways to install yarn: using `npm install --global yarn`, or installing a binary file. Which did you use?

**Comment by Leurus** [comment]
I used `npm install --global yarn` - also just tried that again to upgrade and I'm getting the same error when trying `yarn build`.

**Comment by Pauan** [comment]
Okay, in that case you have to use `npm update --global yarn` in order to upgrade your yarn. After that your `yarn --version` should show `1.22.10`

Also, what does your `node --version` show? You probably need to [update your Node.js as well](https://nodejs.org/en/download/), since Rollup requires a fairly recent version of Node.js.

**Comment by Leurus** [comment]
My node version is 8.11.1 but I can't upgrade because the download I get from that site requires Windows 8 or 10, whereas I have 7.

**Comment by Pauan** [comment]
That's definitely too old. You can try installing [from here](https://nodejs.org/dist/latest-v13.x/).

**Comment by Leurus** [comment]
That's fixed it. Thanks!
