### ISSUE TITLE
[Bug] Bot is betting 1 salt when in tournament salt mines

### ISSUE THREAD

**Issue by Leurus** [Pauan/SaltyBetBot#4]
You said to report this as a bug in your response to my other post, so I assume this is what you meant? 

I can't remember if this issue happened before I was salty illuminati, but it happens frequently now that I am. The bot will bet 1 salt even when I'm at 4100 salt in tournaments, which is the salt mines amount for a max level salty illuminati account.

**Comment by Pauan** [comment]
Yeah, that's what I meant.

The bot was designed for non-illuminati (since I don't have illuminati), and I knew that the "mine amount" calculations were wrong for illuminati. I'll fix this.

**Comment by Pauan** [comment]
Is your bailout really 4100? According to the SaltyBet website it should be 2650

**Comment by Leurus** [comment]
Yes, 4100 is the maximum bailout.

**Comment by Leurus** [comment]
Not sure where you're seeing 2650. If you click the cog wheel and go to options, then click "salty illuminati perks" it says "$3000 in addition to your level bonus"

**Comment by Pauan** [comment]
@Leurus I was going based on [the FAQ](http://www.saltybet.com/about#collapseNine) which says `1000 + level bonus + illuminati bonus`, and the [levels page](http://www.saltybet.com/leveling), which says `550 + 1100`. I guess that's for non-illuminati. I'll update it to 4,100

**Comment by Pauan** [comment]
I have fixed this. Please follow these steps for upgrading:

https://github.com/Pauan/SaltyBetBot#how-to-upgrade

You should see much better performance in tournaments, though I still need to implement the other suggestions you made.
