### ISSUE TITLE
Bot has stopped betting (Brave)

### ISSUE THREAD

**Issue by Leurus** [Pauan/SaltyBetBot#44]
Here's a screenshot of the console. Getting the same source map warning when checking background.html on the extensions page.

![image](https://user-images.githubusercontent.com/26194213/159379068-f54b2154-0182-42fa-bb6a-bd414aeb88b8.png)

**Comment by Pauan** [comment]
I don't see anything wrong with that screenshot, everything seems to be in order. And the bot is working correctly for me. Make sure you are signed in, and maybe try refreshing the page.

**Comment by Leurus** [comment]
Started working again on its own. Weird. I already tried refreshing and re-logging and it didn't work before. 

It looks like it stopped betting in the middle of matchmaking after making a bunch of 1 salt bets (despite having plenty of data) then started betting again 30 minutes later, still on the same matchmaking pool. Wonder what could have caused this?

**Comment by Pauan** [comment]
If WAIFU4u dies, it can't make bets anymore, so it falls back to making $1 bets (to gain experience). WAIFU4u dies occasionally, so that's probably what it was.

**Comment by Leurus** [comment]
Makes sense. Thanks for the clarification!
