### ISSUE TITLE
[Bug?] Betting too much

### ISSUE THREAD

**Issue by Leurus** [Pauan/SaltyBetBot#5]
I updated a couple days ago (the update before your most recent update) and now the bot is betting up to 185k per bet instead of the 40k it was betting before. I definitely think it should bet more than 40k maximum, but not 185k as that starts to affect the odds in the way you spoke about a few months ago.

I would recommend setting the max bet at 70k, this way it's maximizing profits while betting an amount that won't affect the odds much in any scenario. 40k is too low, but 185k is too high.

**Comment by Pauan** [comment]
I already fixed it to bet a maximum of 50k, so upgrade again.
