### ISSUE TITLE
The bot won't bet?

### ISSUE THREAD

**Issue by slippyyy** [Pauan/SaltyBetBot#8]
I did all the steps listed and even have the extension at the upper right corner. Salty bet opens up another twitch.tv tab, but the bot won't make any bets?

**Comment by slippyyy** [comment]
Nevermind. I got it working. Thanks a lot! :)

**Comment by Pauan** [comment]
Could you explain more? Do you get any errors in the console?

Keep in mind that it does not bet on Exhibitions, only Matchmaking and Tournaments.

**Comment by slippyyy** [comment]
I get these two errors in Chrome extensions

Error: No tab with id: 86.
panicked at 'explicit panic', C:\Users\Pauan\.cargo\registry\src\github.com-1ecc6299db9ec823\stdweb-0.4.17\src\webcore\promise_future.rs:131:5

**Comment by Pauan** [comment]
The code has changed a lot since then, do you still have this issue with the latest version?

**Comment by Pauan** [comment]
It's been a while, and I've made a lot of changes since then, so I'm going to assume that this is fixed. But please let me know if you're still running into issues and I'll reopen this.
