### ISSUE TITLE
Chrome Crashing After Update

### ISSUE THREAD

**Issue by Leurus** [Pauan/SaltyBetBot#9]
Chrome is crashing the moment I open my Saltybet profile after updating SaltyBetBot. Not only my SaltyBetBot windows crash, but all of my chrome windows crash the moment I open the profile. It crashes regardless of whether I open the SaltyBet website first, or my chrome start page first (I'm not sure if the bot only loads if you visit SaltyBet)

I have no way to check for errors because it's crashing before I can do anything. Any advice?

If you could provide me a way to revert to the previous version in the meantime I'd appreciate it.

**Comment by Pauan** [comment]
What OS are you using? If you check your task manager, is Chrome using a lot of memory before it crashes?

**Comment by Leurus** [comment]
I'm on Windows 7. It spikes to 500MB of memory (double what it's normally at) then crashes within 0.5-1 second.

**Comment by Pauan** [comment]
It sounds like you have plenty of RAM. What's your Chrome version?

**Comment by Leurus** [comment]
Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by Leurus** [comment]
I just loaded SaltyBetBot into Brave browser and it's now working fine. I guess I'll use that until we can figure this issue out.

**Comment by Pauan** [comment]
It's been a while, and I've made a lot of changes since then, so I'm going to assume that this is fixed. But please let me know if you're still running into issues and I'll reopen this.
